CREATE TABLE CLIENTES (
  ID NUMBER PRIMARY KEY,
  NOMBRE VARCHAR2(50) NOT NULL,
  APELLIDO VARCHAR2(50) NOT NULL,
  TELEFONO VARCHAR2(20) NOT NULL
);

CREATE TABLE MASCOTAS (
  ID NUMBER PRIMARY KEY,
  NOMBRE VARCHAR2(50) NOT NULL,
  ESPECIE VARCHAR2(50) NOT NULL,
  RAZA VARCHAR2(50) NOT NULL,
  EDAD NUMBER NOT NULL,
  CLIENTE_ID NUMBER NOT NULL,
  CONSTRAINT FK_MASCOTAS_CLIENTES
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID)
);

CREATE TABLE CITAS (
  ID NUMBER PRIMARY KEY,
  FECHA DATE NOT NULL,
  MOTIVO VARCHAR2(200) NOT NULL,
  MASCOTA_ID NUMBER NOT NULL,
  CONSTRAINT FK_CITAS_MASCOTAS
    FOREIGN KEY (MASCOTA_ID) REFERENCES MASCOTAS(ID)
);